### ISSUE TITLE
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by 582856** [StanleyLsx/sequence_labeling#66]
Traceback (most recent call last):
File "main.py", line 70, in
dataManager = DataManager(configs, logger)
File "/root/ner/engines/data.py", line 56, in init
self.tokenizer = BertTokenizer.from_pretrained(huggingface_tag)
File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1672, in from_pretrained
resolved_vocab_files[file_id] = cached_path(
File "/root/miniconda3/lib/python3.8/site-packages/transformers/file_utils.py", line 1271, in cached_path
output_path = get_from_cache(
File "/root/miniconda3/lib/python3.8/site-packages/transformers/file_utils.py", line 1494, in get_from_cache
raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

how to solve it

**Comment by 582856** [comment]
use_pretrained_model=True
pretrained_model=Bert
# Bert/AlBert
huggingface_tag=bert-base-chinese
# huggingface上模型的名字
finetune=True
